#!/usr/bin/env bash
# sync-instructions.sh — home/AGENTS.md を正本に、各ハーネスの指示書を生成・検証する(冪等)。
#   生成: claude/CLAUDE.md (home/claude-header.md から)
#         ~/.hermes/SOUL.md (home/soul-core.md から。Hermesは毎メッセージ再読込・restart不要)
#   検証: 生成物ドリフトに加え、指示書symlink配線(~/AGENTS.md, ~/CLAUDE.md,
#         ~/.claude/CLAUDE.md, ~/.codex/AGENTS.md)の健全性を毎回確認する。
#   usage: sync-instructions.sh [--dry-run|--check]   (乖離検出時は exit 3)
#   運用: bash ~/.agents/sync-skills.sh && bash "$(dirname "$0")/sync-instructions.sh"
set -euo pipefail
ROOT="$HOME/workspace/agents-setup"
CORE="$ROOT/home/AGENTS.md"
CLA_HEADER="$ROOT/home/claude-header.md"
SOUL_CORE="$ROOT/home/soul-core.md"
CLA_OUT="$ROOT/claude/CLAUDE.md"
SOUL_OUT="$HOME/.hermes/SOUL.md"
GEN_MARK="<!-- GENERATED by scripts/sync-instructions.sh — DO NOT HAND-EDIT. Edit home/claude-header.md / home/soul-core.md (core: home/AGENTS.md) and re-run. -->"

MODE="${1:-write}"
DRIFT=0

render_claude() {
  printf '%s\n\n' "$GEN_MARK"
  cat "$CLA_HEADER"
}
# SOUL.md はシステムプロンプトとして素で注入されるため、識別マークは末尾に置く
render_soul() {
  cat "$SOUL_CORE"
  printf '\n%s\n' "$GEN_MARK"
}

emit() { # $1=renderer $2=dest
  local tmp
  tmp="$(mktemp)"
  "$1" >"$tmp"
  if [ -e "$2" ] && cmp -s "$tmp" "$2"; then
    echo "unchanged: $2"
    rm -f "$tmp"
    return 0
  fi
  case "$MODE" in
    --check)   echo "DRIFT: $2"; DRIFT=1; rm -f "$tmp" ;;
    --dry-run) echo "would write: $2"; rm -f "$tmp" ;;
    *)
      [ -e "$2" ] && cp "$2" "$2.pre-sync.bak"
      mv "$tmp" "$2"
      echo "written: $2"
      ;;
  esac
}

check_link() { # $1=symlink $2=期待する解決先
  local got want
  got="$(/usr/bin/readlink -f "$1" 2>/dev/null || true)"
  want="$(/usr/bin/readlink -f "$2" 2>/dev/null || true)"
  if [ -z "$got" ] || [ "$got" != "$want" ]; then
    echo "LINK BROKEN: $1 -> ${got:-<missing>} (expected $want)"
    DRIFT=1
  fi
}

[ -r "$CORE" ] || { echo "missing core: $CORE" >&2; exit 1; }
[ -r "$CLA_HEADER" ] || { echo "missing: $CLA_HEADER" >&2; exit 1; }
[ -r "$SOUL_CORE" ] || { echo "missing: $SOUL_CORE" >&2; exit 1; }

emit render_claude "$CLA_OUT"
if [ -d "$HOME/.hermes" ]; then
  emit render_soul "$SOUL_OUT"
fi

check_link "$HOME/AGENTS.md" "$CORE"
check_link "$HOME/CLAUDE.md" "$CORE"
check_link "$HOME/.claude/CLAUDE.md" "$CLA_OUT"
check_link "$HOME/.codex/AGENTS.md" "$CORE"

if [ "$DRIFT" -ne 0 ]; then
  echo "sync-instructions: DRIFT DETECTED"
  exit 3
fi
echo "sync-instructions: OK ($MODE)"
